url: http://rockportsoft.com
# baseurl: /

# Site settings
title: Rockport Software
email: info@rockportsoft.com
description: "Enabling the Intelligent Enterprise"


# Social networks usernames
social:
  - title: twitter
    url: http://twitter.com/rockportsoft
  - title: linkedin
    url: https://www.linkedin.com/company/rockport-software

# Postal address 
address:
  - line: 126 Fairlie Road, 
  - line: Slough, 
  - line: Berkshire, 
  - line: SL1 4PY, 
  - line: United Kingdom
#  - line: tel +44 (0) 1753 577201

# Postal address 
telephone:
  - line: tel +44 (0) 1753 577201
  
# Build settings
markdown: kramdown
permalink: pretty
